name: Build and deploy the Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    working-directory: ./frontend

jobs:
  lint_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npm run lint --if-present

      - name: Unit Testing
        run: npm run test --if-present

  build_frontend:
    runs-on: ubuntu-latest
    needs: lint_and_test

    env:
      VITE_BACKEND_API_URL: ${{secrets.VITE_BACKEND_API_URL}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker build and push
        run: |
          #run commands to build and push docker images
          docker build --build-arg BACKEND_API_URL: ${{secrets.BACKEND_API_URL}} -t hut_finder_frontend .
          docker tag hut_finder_frontend mesutempire/hut_finder_frontend:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push mesutempire/hut_finder_frontend:latest
        env:
          DOCKER_CLI_ACI: 1


