name: Build and deploy the Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    working-directory: frontend

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm install

      - name: Debug Working Directory Contents
        run: ls -la


      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build
          start: npm run preview

      #      - name: Linting
      #        run: npm run lint --if-present

#      - name: Coverage
#        run: npm run coverage --if-present

  build_frontend:
    runs-on: ubuntu-latest
    needs: lint_and_test

    env:
      VITE_BACKEND_API_URL: ${{secrets.VITE_BACKEND_API_URL}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker build and push
        run: |
          #run commands to build and push docker images
          docker build --build-arg BACKEND_API_URL=${{secrets.BACKEND_API_URL}} -t hut_finder_frontend .
          docker tag hut_finder_frontend hfindr.azurecr.io/hut_finder_frontend
          docker login hfindr.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push hfindr.azurecr.io/hut_finder_frontend:latest
        env:
          DOCKER_CLI_ACI: 1

        


